### ISSUE TITLE
一些字段的含义难以理解

### ISSUE THREAD

**Issue by c2ray** [sysuits/VSensor#1]
1. tab_ldt表中  regularcount和largecount字段的解释尚未给出
2. 为什么lineId的值会出现负数, 甚至有的lineId特别长, 而有的只是个位数?
3. 为什么同一个时间间隔会出现多次, 而且每次对应的其他字段的值也有差异?
![image](https://user-images.githubusercontent.com/55729509/73946657-3cc52680-4931-11ea-92e8-efe97f712a63.png)
4. 能详细介绍下posm和ftnode吗?, 不太能理解
5. 渗透率的概念是什么?(是浮动车占所有车的比例, 还是漏记的车量占比)
6. 测量断面流量需要考虑路段中间部分的断面吗?(还是说测量路段的首尾断面即可)
7.  测试集的数据指的是什么?

**Comment by ymnwang** [comment]
请查看新增pdf数据说明文档
